### ISSUE TITLE
can not send queried mails

### ISSUE THREAD

**Issue by philippeaellig** [magenest-dev/module-ultimate-follow-up-email#1]
## Expected Behavior
I created a trigger rule with type order_is_placed and placed an order in the store. In the email Log, i can see my queued email. Then, i expect, that the email will be send by running the send now action. the preview of my email work as expected.

## Actual Behavior
If i run the send action for a queued email, the script will run into an error 500.
`PHP Fatal error:  Uncaught Error: Call to a member function setMessageType() on null in vendor/magenest/module-ultimate-follow-up-email/Model/Mail/TransportBuilder.php:142
Stack trace:
#0 vendor/magento/framework/Mail/Template/TransportBuilder.php(337): Magenest\UltimateFollowupEmail\Model\Mail\TransportBuilder->prepareMessage()
#1 generated/code/Magenest/UltimateFollowupEmail/Model/Mail/TransportBuilder/Interceptor.php(258): Magento\Framework\Mail\Template\TransportBuilder->getTransport()
#2 vendor/magenest/module-ultimate-follow-up-email/Model/Mail.php(251): Magenest\UltimateFollowupEmail\Model\Mail\TransportBuilder\Interceptor->getTransport()
#3 vendor/magenest/module-ultimate-follow-up-email/Model/Mail.php(139): Magenest\UltimateFollowupEmail\Model\Mail->sendMail()
#4 vendor/ in vendor/magenest/module-ultimate-follow-up-email/Model/Mail/TransportBuilder.php on line 142`
the same behavior if i run the cron job.

## Steps to Reproduce the Problem

  1. create a trigger rule with type order_is_placed
  2. place an order
  3. run action "send now" in email log or cron job

## Specifications

  - Version: Magento 2.3.3 and magenest/module-ultimate-follow-up-email 100.3
  - php 7.2
  - magento is in development mode

**Comment by philippeaellig** [comment]
I think, you made changes to the prepareMessage method of the TransportBuilder class. And $this->message was defined in the constructor in magento 2.2. But in Magento 2.3, message is defined in the prepareMessage method. i think, the mailing will run on magento 2.2, but not on magento 2.3.

**Comment by azinkey** [comment]
same error for me too using Magento 2.3.3
